[package]
name = "budokan_extensions"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.10.1"
openzeppelin_introspection = "1.0.0"

[tool.snforge]
# exit_first = true

[dev-dependencies]
snforge_std = "0.45.0"

[scripts]
test = "snforge test"

[[target.starknet-contract]]
sierra = true
casm = true

[lib]